### ISSUE TITLE
切换国内源，升级node,npm版本都没解决

### ISSUE THREAD

**Issue by Rickmoti** [dragonir/threejs-odessey#4]
npm ERR! code ETIMEDOUT
npm ERR! syscall connect
npm ERR! errno ETIMEDOUT
npm ERR! network request to http://npm.tech.21cn.com/yocto-queue/-/yocto-queue-0.1.0.tgz failed, reason: connect ETIMEDOUT 14.29.118.118:80
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.

**Comment by Rickmoti** [comment]
解决了

**Comment by 8k89** [comment]
请问这个解决的办法是什么
